const ROLES = Object.freeze({
  SYSTEM_ADMIN: "system_admin",
  MAINTENANCE_SUPERVISOR: "maintenance_supervisor",
  SCHEDULER: "scheduler",
  TECHNICIAN: "technician",
  WAREHOUSE_STAFF: "warehouse_staff",
  VIEWER: "viewer",
});

const ALL_ROLES = Object.freeze(Object.values(ROLES));

const ROLE_POLICIES = Object.freeze({
  READ: ALL_ROLES,
  MASTER_WRITE: Object.freeze([ROLES.SYSTEM_ADMIN, ROLES.MAINTENANCE_SUPERVISOR]),
  SCHEDULE_WRITE: Object.freeze([ROLES.SYSTEM_ADMIN, ROLES.MAINTENANCE_SUPERVISOR, ROLES.SCHEDULER]),
  PACKAGE_WRITE: Object.freeze([ROLES.SYSTEM_ADMIN, ROLES.MAINTENANCE_SUPERVISOR, ROLES.SCHEDULER]),
  BACKFILL_WRITE: Object.freeze([ROLES.SYSTEM_ADMIN, ROLES.MAINTENANCE_SUPERVISOR, ROLES.TECHNICIAN]),
  WORK_ORDER_WRITE: Object.freeze([ROLES.SYSTEM_ADMIN, ROLES.MAINTENANCE_SUPERVISOR, ROLES.TECHNICIAN]),
  INVENTORY_POST: Object.freeze([ROLES.SYSTEM_ADMIN, ROLES.MAINTENANCE_SUPERVISOR, ROLES.WAREHOUSE_STAFF]),
  INVENTORY_CONSUME: Object.freeze([
    ROLES.SYSTEM_ADMIN,
    ROLES.MAINTENANCE_SUPERVISOR,
    ROLES.WAREHOUSE_STAFF,
    ROLES.TECHNICIAN,
  ]),
  ASSET_WRITE: Object.freeze([ROLES.SYSTEM_ADMIN, ROLES.MAINTENANCE_SUPERVISOR, ROLES.WAREHOUSE_STAFF]),
  TURNAROUND_WRITE: Object.freeze([
    ROLES.SYSTEM_ADMIN,
    ROLES.MAINTENANCE_SUPERVISOR,
    ROLES.TECHNICIAN,
    ROLES.WAREHOUSE_STAFF,
  ]),
  TURNAROUND_SUPERVISE: Object.freeze([ROLES.SYSTEM_ADMIN, ROLES.MAINTENANCE_SUPERVISOR]),
  TURNAROUND_RETURN: Object.freeze([ROLES.SYSTEM_ADMIN, ROLES.MAINTENANCE_SUPERVISOR, ROLES.WAREHOUSE_STAFF]),
  DATABASE_ADMIN: Object.freeze([ROLES.SYSTEM_ADMIN]),
});

function roleAllowed(role, policy) {
  return Boolean(role && policy.includes(role));
}

module.exports = { ROLES, ALL_ROLES, ROLE_POLICIES, roleAllowed };
